repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: fix-byte-order-marker
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.23.3
    hooks:
    - id: pyupgrade
      args: ["--py36-plus"]
  - repo: https://github.com/ambv/black
    rev: 21.7b0
    hooks:
    - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
      - id: isort
